from __future__ import annotations

from dataclasses import dataclass
from typing import Mapping


CANONICAL_FIELDS = frozenset(
    {
        "target",
        "distance",
        "power",
        "damage",
        "bullet_id",
        "aim_mode",
        "gun_mode",
        "movement_mode",
        "mode",
        "evasion",
        "evading",
        "wall_risk",
        "reason",
    }
)


@dataclass(frozen=True)
class TelemetryEventSpec:
    category: str
    required_fields: tuple[str, ...] = ()
    optional_fields: tuple[str, ...] = ()
    aliases: Mapping[str, tuple[str, ...]] | None = None

    def normalized_fields(self, fields: Mapping[str, object]) -> dict[str, object]:
        normalized = dict(fields)
        for canonical, aliases in (self.aliases or {}).items():
            if normalized.get(canonical) not in (None, ""):
                continue
            for alias in aliases:
                if fields.get(alias) not in (None, ""):
                    normalized[canonical] = fields[alias]
                    break
        return normalized


EVENT_SPECS: dict[str, TelemetryEventSpec] = {
    "telemetry.session": TelemetryEventSpec("lifecycle"),
    "telemetry.dropped": TelemetryEventSpec("lifecycle", required_fields=("count",)),
    "bot.config": TelemetryEventSpec(
        "lifecycle",
        optional_fields=(
            "selectable_guns",
            "force_guns",
            "forced_gun",
            "eval_waves",
            "fire_utility_shadow",
        ),
    ),
    "battle.reset": TelemetryEventSpec("lifecycle", optional_fields=("rounds", "game_type")),
    "round.reset": TelemetryEventSpec("lifecycle", optional_fields=("previous_turn", "current_turn")),
    "bot.turn_timing": TelemetryEventSpec(
        "lifecycle",
        required_fields=("decision_elapsed_us", "severity"),
        optional_fields=(
            "turn_timeout_us",
            "time_left_us_before_go",
            "target",
            "known_targets",
            "gun_heat",
            "gun_samples",
            "gun_waves",
            "eval_waves",
            "movement_waves",
            "shadow_bullets",
            "movement_mode",
            "aim_mode",
        ),
    ),
    "bot.skipped_turn": TelemetryEventSpec(
        "lifecycle",
        required_fields=("skipped_turn",),
        optional_fields=(
            "current_turn",
            "last_decision_elapsed_us",
            "last_time_left_us_before_go",
            "turn_timeout_us",
            "time_left_us",
            "target",
            "known_targets",
            "gun_heat",
            "gun_samples",
            "gun_waves",
            "eval_waves",
            "movement_waves",
            "shadow_bullets",
            "movement_mode",
            "aim_mode",
        ),
    ),
    "scan.new": TelemetryEventSpec(
        "targeting",
        optional_fields=("bot_id", "energy", "x", "y"),
        aliases={"target": ("bot_id",)},
    ),
    "scan.reacquired": TelemetryEventSpec(
        "targeting",
        optional_fields=("bot_id", "previous_age", "previous_x", "previous_y", "x", "y"),
        aliases={"target": ("bot_id",)},
    ),
    "target.select": TelemetryEventSpec(
        "targeting",
        required_fields=("selected",),
        optional_fields=("previous", "score", "fresh_candidates", "candidate", "candidate_score", "previous_age", "known_targets"),
        aliases={"target": ("selected",)},
    ),
    "target.drop_lost": TelemetryEventSpec(
        "targeting",
        optional_fields=("bot_id", "age", "cached_x", "cached_y", "cached_distance", "known_targets"),
        aliases={"target": ("bot_id",)},
    ),
    "target.stale": TelemetryEventSpec("targeting", optional_fields=("bot_id",), aliases={"target": ("bot_id",)}),
    "target.dead": TelemetryEventSpec("targeting", optional_fields=("bot_id",), aliases={"target": ("bot_id",)}),
    "target.reacquire": TelemetryEventSpec("targeting", optional_fields=("target", "age", "distance", "radar_mode")),
    "search": TelemetryEventSpec("targeting", optional_fields=("known_targets",)),
    "search.wall_avoid": TelemetryEventSpec("movement", optional_fields=("x", "y", "center_bearing", "evade_direction", "near_wall")),
    "track": TelemetryEventSpec(
        "fire",
        required_fields=("target", "distance", "gun_bearing", "aim_mode"),
        optional_fields=(
            "age",
            "radar_bearing",
            "radar_turn",
            "radar_mode",
            "radar_target",
            "radar_age",
            "predicted_x",
            "predicted_y",
            "aim_guess_factor",
            "traditional_gf_global",
            "traditional_gf_global_weight",
            "traditional_gf_segment",
            "traditional_gf_segment_weight",
            "traditional_gf_blend",
            "traditional_gf_selected",
            "traditional_gf_source",
            "gun_samples",
            "gun_scores",
            "dynamic_cluster_selected_guess_factor",
            "dynamic_cluster_shot_quality",
            "dynamic_cluster_quality_reason",
            "dynamic_cluster_recommended_power_scale",
            "firepower",
            "hold_reason",
            "fire_alignment_limit",
            "movement_mode",
            "known_targets",
        ),
        aliases={"power": ("firepower",), "reason": ("hold_reason",)},
    ),
    "gun.switch": TelemetryEventSpec(
        "fire",
        required_fields=("selected",),
        optional_fields=("target", "previous", "scores"),
        aliases={"aim_mode": ("selected",), "gun_mode": ("selected",)},
    ),
    "gun.switch_decision": TelemetryEventSpec(
        "fire",
        required_fields=("selected",),
        optional_fields=("target", "previous", "changed", "candidates"),
    ),
    "gun.traditional_gf_profile": TelemetryEventSpec(
        "fire",
        required_fields=("target",),
        optional_fields=(
            "aim_mode",
            "global_guess_factor",
            "global_weight",
            "segment_guess_factor",
            "segment_weight",
            "blend",
            "selected_guess_factor",
            "source",
            "profile_key",
        ),
    ),
    "gun.wave_visit": TelemetryEventSpec(
        "fire",
        optional_fields=(
            "target",
            "guess_factor",
            "samples",
            "traveled",
            "distance",
            "selected_gun",
            "virtual_scores",
            "gun_scores",
            "fire_context_tags",
            "fire_context_flight_time",
            "fire_context_lateral_direction",
            "fire_context_lateral_speed_signed",
            "fire_context_lateral_confidence",
            "fire_context_wall_margin",
            "fire_context_wall_escape_balance",
            "fire_context_positive_escape_angle",
            "fire_context_negative_escape_angle",
            "fire_context_distance_bucket",
            "fire_context_firepower_bucket",
            "dynamic_cluster_neighbor_count",
            "dynamic_cluster_avg_neighbor_distance",
            "dynamic_cluster_neighbor_distance_min",
            "dynamic_cluster_neighbor_distance_max",
            "dynamic_cluster_tag_match_ratio",
            "dynamic_cluster_avg_flight_time_delta",
            "dynamic_cluster_avg_wall_escape_delta",
            "dynamic_cluster_avg_lateral_confidence",
            "dynamic_cluster_density_score",
            "dynamic_cluster_selected_guess_factor",
            "dynamic_cluster_effective_bandwidth",
            "dynamic_cluster_best_bin_guess_factor",
            "dynamic_cluster_peak_margin",
            "dynamic_cluster_neighbor_agreement",
            "dynamic_cluster_aim_confidence",
            "dynamic_cluster_best_peak_gf",
            "dynamic_cluster_best_peak_score",
            "dynamic_cluster_second_peak_gf",
            "dynamic_cluster_second_peak_score",
            "dynamic_cluster_peak_separation",
            "dynamic_cluster_peak_score_ratio",
            "dynamic_cluster_ambiguous_peak",
            "dynamic_cluster_shot_quality",
            "dynamic_cluster_quality_reason",
            "dynamic_cluster_recommended_power_scale",
            "traditional_gf_guess_factor",
            "traditional_gf_error",
            "traditional_gf_abs_error",
            "traditional_gf_source",
            "traditional_gf_profile_key",
            "traditional_gf_segment_weight",
            "traditional_gf_context_flight_time",
            "traditional_gf_context_wall_escape_balance",
            "traditional_gf_context_lateral_confidence",
            "traditional_gf_context_tags",
            "anti_surfer_context_relevance",
            "anti_surfer_wall_escape_balance",
            "anti_surfer_context_tags",
            "displacement_context_flight_time",
            "displacement_wall_escape_balance",
            "displacement_context_tags",
            "displacement_replay_count",
            "displacement_candidate_score",
            "displacement_peak_density",
            "displacement_peak_share",
            "displacement_bearing_spread",
            "displacement_distance_bucket",
            "linear_context_flight_time",
            "linear_context_lateral_confidence",
            "linear_context_short_flight_time",
            "linear_context_tags",
            "linear_wall_aware_wall_hit",
            "linear_wall_aware_ticks",
            "linear_wall_aware_final_speed",
        ),
        aliases={"aim_mode": ("selected_gun",), "gun_mode": ("selected_gun",)},
    ),
    "gun.eval_wave_visit": TelemetryEventSpec(
        "fire",
        optional_fields=(
            "target",
            "guess_factor",
            "samples",
            "traveled",
            "distance",
            "selected_gun",
            "virtual_scores",
            "gun_scores",
            "fire_context_tags",
            "fire_context_flight_time",
            "fire_context_lateral_direction",
            "fire_context_lateral_speed_signed",
            "fire_context_lateral_confidence",
            "fire_context_wall_margin",
            "fire_context_wall_escape_balance",
            "fire_context_positive_escape_angle",
            "fire_context_negative_escape_angle",
            "fire_context_distance_bucket",
            "fire_context_firepower_bucket",
            "dynamic_cluster_neighbor_count",
            "dynamic_cluster_avg_neighbor_distance",
            "dynamic_cluster_neighbor_distance_min",
            "dynamic_cluster_neighbor_distance_max",
            "dynamic_cluster_tag_match_ratio",
            "dynamic_cluster_avg_flight_time_delta",
            "dynamic_cluster_avg_wall_escape_delta",
            "dynamic_cluster_avg_lateral_confidence",
            "dynamic_cluster_density_score",
            "dynamic_cluster_selected_guess_factor",
            "dynamic_cluster_effective_bandwidth",
            "dynamic_cluster_best_bin_guess_factor",
            "dynamic_cluster_peak_margin",
            "dynamic_cluster_neighbor_agreement",
            "dynamic_cluster_aim_confidence",
            "dynamic_cluster_best_peak_gf",
            "dynamic_cluster_best_peak_score",
            "dynamic_cluster_second_peak_gf",
            "dynamic_cluster_second_peak_score",
            "dynamic_cluster_peak_separation",
            "dynamic_cluster_peak_score_ratio",
            "dynamic_cluster_ambiguous_peak",
            "dynamic_cluster_shot_quality",
            "dynamic_cluster_quality_reason",
            "dynamic_cluster_recommended_power_scale",
            "traditional_gf_guess_factor",
            "traditional_gf_error",
            "traditional_gf_abs_error",
            "traditional_gf_source",
            "traditional_gf_profile_key",
            "traditional_gf_segment_weight",
            "traditional_gf_context_flight_time",
            "traditional_gf_context_wall_escape_balance",
            "traditional_gf_context_lateral_confidence",
            "traditional_gf_context_tags",
            "anti_surfer_context_relevance",
            "anti_surfer_wall_escape_balance",
            "anti_surfer_context_tags",
            "displacement_context_flight_time",
            "displacement_wall_escape_balance",
            "displacement_context_tags",
            "displacement_replay_count",
            "displacement_candidate_score",
            "displacement_peak_density",
            "displacement_peak_share",
            "displacement_bearing_spread",
            "displacement_distance_bucket",
            "linear_context_flight_time",
            "linear_context_lateral_confidence",
            "linear_context_short_flight_time",
            "linear_context_tags",
            "linear_wall_aware_wall_hit",
            "linear_wall_aware_ticks",
            "linear_wall_aware_final_speed",
        ),
        aliases={"aim_mode": ("selected_gun",), "gun_mode": ("selected_gun",)},
    ),
    "bullet.fired": TelemetryEventSpec(
        "fire",
        required_fields=("bullet_id", "power", "aim_mode"),
        optional_fields=(
            "target",
            "direction",
            "energy",
            "gun_waves",
            "gun_samples",
            "gun_confidence",
            "gun_confidence_visits",
            "selected_gun_confidence",
            "selected_gun_confidence_visits",
            "traditional_gf_source",
            "target_age",
            "target_x",
            "target_y",
            "wave",
            "shadow_bullets",
        ),
    ),
    "bullet.hit_bot": TelemetryEventSpec(
        "fire",
        required_fields=("bullet_id", "power", "damage", "energy"),
        optional_fields=("victim", "target", "aim_mode", "traditional_gf_source"),
        aliases={"target": ("victim",)},
    ),
    "bullet.resolved": TelemetryEventSpec(
        "combat",
        required_fields=("bullet_id", "power", "outcome"),
        optional_fields=("target", "fired_turn", "resolved_turn", "damage", "aim_mode", "source"),
    ),
    "bullet.resolution_corrected": TelemetryEventSpec(
        "combat",
        required_fields=("bullet_id", "power", "outcome", "previous_outcome"),
        optional_fields=("target", "fired_turn", "resolved_turn", "damage", "aim_mode", "source"),
    ),
    "fire.utility_opportunity": TelemetryEventSpec(
        "combat",
        required_fields=(
            "action",
            "reason",
            "aim_mode",
            "distance",
            "range_band",
            "power_band",
            "quality_band",
            "q",
            "calibration_support",
            "calibration_hits",
            "fallback_level",
            "power",
            "bullet_damage",
            "hit_bonus",
            "gun_heat",
            "cooling_rate",
            "cooldown_turns",
            "score_utility",
            "energy_swing_utility",
        ),
        optional_fields=("target", "solution_quality", "model_support"),
    ),
    "fire.utility_accepted": TelemetryEventSpec(
        "combat",
        required_fields=(
            "bullet_id",
            "action",
            "reason",
            "aim_mode",
            "distance",
            "range_band",
            "power_band",
            "quality_band",
            "q",
            "calibration_support",
            "calibration_hits",
            "fallback_level",
            "power",
            "bullet_damage",
            "hit_bonus",
            "gun_heat",
            "cooling_rate",
            "cooldown_turns",
            "score_utility",
            "energy_swing_utility",
        ),
        optional_fields=(
            "target",
            "fired_turn",
            "solution_quality",
            "model_support",
        ),
    ),
    "fire.utility_outcome": TelemetryEventSpec(
        "combat",
        required_fields=(
            "bullet_id",
            "outcome",
            "hit",
            "damage",
            "q",
            "calibration_support",
            "calibration_hits",
            "fallback_level",
            "power",
        ),
        optional_fields=(
            "target",
            "action",
            "reason",
            "fired_turn",
            "resolved_turn",
            "aim_mode",
            "distance",
            "range_band",
            "power_band",
            "quality_band",
            "solution_quality",
            "model_support",
            "bullet_damage",
            "hit_bonus",
            "gun_heat",
            "cooling_rate",
            "cooldown_turns",
            "score_utility",
            "energy_swing_utility",
        ),
    ),
    "fire.utility_outcome_corrected": TelemetryEventSpec(
        "combat",
        required_fields=(
            "bullet_id",
            "outcome",
            "previous_outcome",
            "hit",
            "damage",
            "q",
            "calibration_support",
            "calibration_hits",
            "fallback_level",
            "power",
        ),
        optional_fields=(
            "target",
            "action",
            "reason",
            "fired_turn",
            "resolved_turn",
            "aim_mode",
            "distance",
            "range_band",
            "power_band",
            "quality_band",
            "solution_quality",
            "model_support",
            "bullet_damage",
            "hit_bonus",
            "gun_heat",
            "cooling_rate",
            "cooldown_turns",
            "score_utility",
            "energy_swing_utility",
        ),
    ),
    "gun.fire_drift": TelemetryEventSpec(
        "fire",
        required_fields=("bullet_id",),
        optional_fields=(
            "target",
            "aim_mode",
            "planned_x",
            "planned_y",
            "actual_x",
            "actual_y",
            "source_error",
            "planned_direction",
            "actual_direction",
            "direction_error",
            "abs_direction_error",
            "planned_power",
            "actual_power",
            "power_error",
            "planned_speed",
            "actual_speed",
            "speed_error",
        ),
    ),
    "enemy.fire_detected": TelemetryEventSpec(
        "energy",
        required_fields=("power", "distance", "evasion"),
        optional_fields=(
            "bot_id",
            "raw_drop",
            "corrected_drop",
            "correction",
            "scan_gap",
            "bullet_travel_ticks",
            "evading",
            "evade_direction",
            "move_direction",
            "evade_until",
            "movement_wave",
            "predicted_power",
            "prediction_confidence",
            "prediction_reason",
            "prediction_error",
            "detection_confidence",
            "power_samples",
            "power_mae",
            "inferred_fire_turn",
            "fire_source_x",
            "fire_source_y",
            "fire_source_offset",
        ),
        aliases={"target": ("bot_id",)},
    ),
    "enemy.energy_drop_ignored": TelemetryEventSpec(
        "energy",
        required_fields=("reason",),
        optional_fields=("bot_id", "raw_drop", "corrected_drop", "correction", "scan_gap", "distance"),
        aliases={"target": ("bot_id",)},
    ),
    "enemy.gun_heat_wave": TelemetryEventSpec(
        "energy",
        required_fields=("power", "distance", "reason"),
        optional_fields=("bot_id", "confidence", "samples", "power_mae", "target_age", "movement_wave"),
        aliases={"target": ("bot_id",)},
    ),
    "movement.profile_visit": TelemetryEventSpec(
        "movement",
        optional_fields=(
            "target", "guess_factor", "bin", "bucket", "visits", "wave_age", "ensemble_danger", "ensemble_samples",
            "evidence_kind", "wave_kind", "occupancy_visits", "hit_profile_support", "match_error",
        ),
    ),
    "movement.flatten": TelemetryEventSpec(
        "movement",
        optional_fields=(
            "target", "current_direction", "suggested_direction", "bucket", "current_count", "alternative_count",
            "distance", "reason", "score_source", "legacy_direction", "selected_current_danger",
            "selected_alternative_danger",
        ),
    ),
    "movement.flatten_shadow": TelemetryEventSpec(
        "movement",
        optional_fields=("target", "current_direction", "suggested_direction", "bucket", "current_count", "alternative_count", "distance", "reason"),
    ),
    "movement.duel_flatten": TelemetryEventSpec("movement", optional_fields=("target", "suggested_direction", "distance")),
    "movement.goto_surf": TelemetryEventSpec(
        "movement",
        optional_fields=(
            "target", "destination_x", "destination_y", "danger", "wave_kind", "turn", "speed",
            "occupancy_danger", "hit_danger", "hit_profile_support", "hit_fallback_level", "expected_pressure",
            "shadow_danger", "shadow_destination_x", "shadow_destination_y", "shadow_direction",
            "shadow_selected_danger", "shadow_differs",
            "live_destination_x", "live_destination_y", "live_direction", "live_selected_danger", "score_source",
        ),
        aliases={"movement_mode": ("mode",)},
    ),
    "movement.evidence_shadow": TelemetryEventSpec(
        "movement",
        required_fields=("live_direction", "shadow_direction", "hit_fallback_level", "score_source"),
        optional_fields=(
            "target", "distance", "current_direction", "shadow_differs", "current_live_danger",
            "alternative_live_danger", "current_occupancy", "alternative_occupancy", "current_hit_danger",
            "alternative_hit_danger", "current_expected_pressure", "alternative_expected_pressure",
            "current_shadow_danger", "alternative_shadow_danger", "hit_profile_support",
            "selected_direction",
        ),
    ),
    "movement.feint": TelemetryEventSpec(
        "movement",
        optional_fields=("target", "mode", "reason", "duration", "move_direction", "near_wall", "variant", "turn_scale"),
    ),
    "movement.duel_potential": TelemetryEventSpec(
        "movement",
        optional_fields=("target", "destination_x", "destination_y", "force_x", "force_y", "distance", "mode", "evading", "turn", "speed"),
        aliases={"movement_mode": ("mode",)},
    ),
    "movement.minimum_risk": TelemetryEventSpec(
        "movement",
        optional_fields=(
            "target",
            "destination_x",
            "destination_y",
            "risk",
            "candidates",
            "nearest_enemy",
            "nearest_enemy_distance",
            "reused_destination",
            "destination_age",
            "turn",
            "speed",
            "known_targets",
            "fire_threat",
        ),
        aliases={"movement_mode": ("mode",)},
    ),
    "wall.avoid": TelemetryEventSpec("movement", optional_fields=("x", "y", "center_bearing", "move_direction", "evade_direction", "target")),
    "separate": TelemetryEventSpec("movement", optional_fields=("target", "distance", "away_bearing", "target_speed", "turn_limit", "move_direction")),
    "hit.bullet": TelemetryEventSpec(
        "combat",
        required_fields=("owner", "power", "damage", "energy"),
        optional_fields=(
            "bullet_direction", "wall_risk", "near_wall", "evade_direction", "move_direction", "evade_until",
            "movement_wave_match", "movement_guess_factor", "movement_bin", "movement_wave_kind",
            "movement_wave_match_error", "movement_hit_profile_support",
        ),
    ),
    "combat.profile": TelemetryEventSpec(
        "combat",
        required_fields=("version", "recent_window_start", "recent_window_end"),
        optional_fields=(
            "target",
            "tags",
            "recent_own_accepted_shots",
            "recent_own_resolved_shots",
            "recent_own_hits",
            "recent_own_misses",
            "recent_own_fired_energy",
            "recent_own_hit_damage",
            "recent_own_hit_rate",
            "recent_own_damage_per_accepted_shot",
            "recent_own_damage_per_fired_energy",
            "recent_own_resolution_coverage",
            "recent_enemy_inferred_shots",
            "recent_enemy_weighted_shots",
            "recent_enemy_average_fire_confidence",
            "recent_enemy_inferred_fired_energy",
            "recent_enemy_weighted_fired_energy",
            "recent_enemy_hits",
            "recent_enemy_hit_damage",
            "recent_enemy_hits_matched",
            "recent_enemy_hit_match_coverage",
            "recent_damage_delta",
            "lifetime_own_accepted_shots",
            "lifetime_own_resolved_shots",
            "lifetime_own_hits",
            "lifetime_own_misses",
            "lifetime_own_fired_energy",
            "lifetime_own_hit_damage",
            "lifetime_own_hit_rate",
            "lifetime_own_damage_per_accepted_shot",
            "lifetime_own_damage_per_fired_energy",
            "lifetime_own_resolution_coverage",
            "lifetime_enemy_inferred_shots",
            "lifetime_enemy_weighted_shots",
            "lifetime_enemy_average_fire_confidence",
            "lifetime_enemy_inferred_fired_energy",
            "lifetime_enemy_weighted_fired_energy",
            "lifetime_enemy_hits",
            "lifetime_enemy_hit_damage",
            "lifetime_enemy_hits_matched",
            "lifetime_enemy_hit_match_coverage",
            "lifetime_damage_delta",
        ),
    ),
    "hit.wall": TelemetryEventSpec("combat", optional_fields=("evade_direction", "move_direction", "center_bearing", "wall_escape_until")),
    "hit.bot": TelemetryEventSpec("combat", optional_fields=("target", "energy", "rammed", "distance", "near_wall", "wall_risk")),
}


EXPECTED_EVASION_LABELS = frozenset({"active_duel", "active_melee", "threat_only"})


def event_spec(event_name: str) -> TelemetryEventSpec | None:
    return EVENT_SPECS.get(event_name)


def normalize_fields(event_name: str, fields: Mapping[str, object]) -> dict[str, object]:
    spec = event_spec(event_name)
    if spec is None:
        return dict(fields)
    return spec.normalized_fields(fields)


def missing_required_fields(event_name: str, fields: Mapping[str, object]) -> tuple[str, ...]:
    spec = event_spec(event_name)
    if spec is None:
        return ()
    normalized = spec.normalized_fields(fields)
    return tuple(field for field in spec.required_fields if normalized.get(field) in (None, ""))
